version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: emurgo
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://dbUser:localdev@db:5432/emurgo
    ports:
      - "3000:3000"

volumes:
  db_data:
